---
- name: AWS CLI query version
  ansible.builtin.command: aws --version
  failed_when: false
  changed_when: false
  register: aws_cli_version

- name: AWS CLI install
  when: aws_cli_version.rc != 0
  block:
    - name: Download and extract installer
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip
        dest: /tmp
        remote_src: true

    - name: Install AWS CLI
      ansible.builtin.command: /tmp/aws/install
      become: true

    - name: Cleanup installer
      ansible.builtin.file:
        path: /tmp/aws
        state: absent

    - name: Verify AWS CLI version
      ansible.builtin.command: aws --version
      changed_when: false
